---
- name: Aplicar Hardening Básico na VPS
  # 'hosts:' aponta para o grupo que definimos no arquivo 'hosts'
  hosts: vps_hostinger 
  
  # 'become: yes' diz ao Ansible para usar 'sudo' 
  # (escalar privilégios) para rodar as tarefas.
  become: yes 

  tasks:
    - name: 1. Atualizar todos os pacotes do sistema (apt)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'yes'
      
    - name: 2. Garantir que o usuário 'hackermel' está no grupo 'sudo'
      ansible.builtin.user:
        name: hackermel
        groups: sudo
        append: yes
        state: present

    - name: 3. Desabilitar login SSH do usuário 'root'
      # Edita a linha 'PermitRootLogin' no arquivo de configuração do SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      # 'notify:' avisa o 'handler' abaixo para rodar
      notify: Reiniciar SSH


    - name: 4. Instalar o UFW (Uncomplicated Firewall)
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: 5. Negar todo tráfego de entrada (Default Deny)
      community.general.ufw:
        default: deny
        direction: incoming

    - name: 6. Permitir todo tráfego de saída
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: 7. Permitir portas essenciais (SSH, HTTP, HTTPS, KeyCloak, Postgres)
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      # 'with_items' roda a tarefa para cada item da lista
      with_items:
        - '22'    # SSH (Crucial!)
        - '80'    # HTTP (para seu site)
        - '443'   # HTTPS (para seu site)
        - '8080'  # Keycloak
        - '5432'  # PostgreSQL
        - '9090'  # Prometheus
        - '3000'  # Grafana
        - '9100'  # Node Exporter 

    - name: 8. Ativar o UFW
      community.general.ufw:
        state: enabled

  # Handlers são tarefas especiais que só rodam se
  # uma tarefa com 'notify' reportar uma mudança.
  handlers:
    - name: Reiniciar SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
